# Generated by Django 6.0.6 on 2026-06-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(choices=[(1, '*'), (2, '*'), (3, '*'), (4, '*'), (5, '*'), (6, '*')], default=3),
        ),
    ]
